Repository kmycode/sangokukmy-client, pull requests merged in 2019-03, with the labels that each got.

#22 3.0のマージ
  src/api/api.ts
  src/common/definitions.ts
  src/components/pages/StatusPage.vue
  src/components/parts/status/TownWarView.vue
  src/models/status/statusmodel.ts
  src/services/notificationservice.ts
Labels: bug, enhancement

#23 3.0.2のマージ
  src/common/definitions.ts
  src/components/parts/status/CommandList.vue
Labels: enhancement

#24 3.1のマージ
  src/api/api.ts
  src/common/definitions.ts
  src/components/pages/StatusPage.vue
  src/components/parts/StatusParameters.vue
  src/components/parts/ThreadBbs.vue
  src/components/parts/status/CommandList.vue
  src/models/status/commandinputer.ts
  src/models/status/statusmodel.ts
  src/models/status/statusparameter.ts
Labels: bug, enhancement

#25 3.2のマージ
  src/App.vue
  src/api/api.ts
  src/api/apistreaming.ts
  src/common/definitions.ts
  src/components/pages/EntryPage.vue
  src/components/pages/StatusPage.vue
  src/components/pages/TopPage.vue
  src/components/parts/SimpleCharacterList.vue
  src/components/parts/StatusParameters.vue
  src/components/parts/UnitPicker.vue
  src/components/parts/status/CommandList.vue
  src/components/parts/status/CustomSoldierTypeView.vue
  src/components/parts/status/UnitView.vue
  src/models/common/ValueUtil.ts
  src/models/status/commandinputer.ts
  src/models/status/commandlist.ts
  src/models/status/soldiertypemodel.ts
  src/models/status/statusmodel.ts
  src/models/status/statusparameter.ts
  src/models/status/statusstore.ts
  src/models/status/unitmodel.ts
  src/services/notificationservice.ts
Labels: bug, enhancement

#26 3.2.1のマージ
  src/common/definitions.ts
  src/components/parts/status/CommandList.vue
Labels: bug

#27 3.3のマージ
  src/api/api.ts
  src/common/definitions.ts
  src/components/pages/EntryPage.vue
  src/components/parts/CharacterIcon.vue
  src/components/parts/CharacterIconPicker.vue
  src/components/parts/SimpleCharacterList.vue
  src/components/parts/status/CustomSoldierTypeView.vue
  src/models/status/soldiertypemodel.ts
  src/models/status/statusmodel.ts
  src/models/status/statusparameter.ts
  src/scss/country-color.scss
Labels: bug, enhancement

#28 3.3.1のマージ
  src/components/pages/EntryPage.vue
Labels: enhancement

#29 3.3.3のマージ
  src/components/pages/StatusPage.vue
Labels: bug

#30 3.3.4のマージ
  src/models/status/commandinputer.ts
Labels: bug

#31 3.3.5のマージ
  src/models/status/commandinputer.ts
Labels: bug

#33 発言手紙に紫色を追加（テスト）
  src/components/parts/KmyChatTagText.vue
Labels: enhancement

#34 3.4のマージ
  README.md
  src/common/definitions.ts
  src/components/pages/EntryPage.vue
  src/components/pages/StatusPage.vue
  src/components/parts/KmyChatTagText.vue
  src/components/parts/status/CustomSoldierTypeView.vue
  src/models/common/arrayutil.ts
  src/models/status/commandinputer.ts
  src/models/status/soldiertypemodel.ts
  src/models/status/statusstore.ts
Labels: bug, enhancement

#32 Update KmyChatTagText.vue
  src/components/parts/KmyChatTagText.vue
Labels: enhancement

#35 3.5のマージ
  src/api/api.ts
  src/components/pages/EntryPage.vue
  src/components/pages/StatusPage.vue
  src/components/pages/TopPage.vue
  src/components/parts/CharacterIconPicker.vue
  src/models/status/statusmodel.ts
  src/services/notificationservice.ts
Labels: bug

#36 3.5.1のマージ
  src/models/status/statusmodel.ts
Labels: enhancement

#37 3.5.2のマージ
  src/models/status/statusmodel.ts
Labels: bug

#38 3.5.3のマージ
  src/components/pages/StatusPage.vue
Labels: bug

#39 3.5.5のマージ
  src/components/parts/CharacterIcon.vue
  src/components/parts/ChatMessagePanel.vue
  src/models/status/chatmessagecontainer.ts
  src/models/status/statusmodel.ts
Labels: enhancement

#41 3.5.8のマージ
  src/App.vue
  src/api/api.ts
  src/common/current.ts
  src/common/definitions.ts
  src/components/pages/EntryPage.vue
  src/components/pages/StatusPage.vue
  src/components/pages/TopPage.vue
  src/components/parts/SimpleCharacterList.vue
  src/models/character/loginservice.ts
  src/models/status/commandinputer.ts
  src/models/status/statusmodel.ts
Labels: bug, enhancement

#42 3.5.12のマージ
  src/api/api.ts
  src/components/pages/EntryPage.vue
  src/components/pages/StatusPage.vue
  src/models/status/statusmodel.ts
Labels: bug, enhancement

#43 3.5.13のマージ
  src/components/pages/StatusPage.vue
Labels: bug

#44 3.6のマージ
  src/api/api.ts
  src/common/definitions.ts
  src/components/pages/StatusPage.vue
  src/models/status/chatmessagecontainer.ts
  src/models/status/commandinputer.ts
  src/models/status/statusmodel.ts
  src/models/status/unitmodel.ts
Labels: bug

#45 3.6.1のマージ
  src/common/definitions.ts
Labels: enhancement

#46 3.7のマージ
  src/common/definitions.ts
  src/models/status/commandlist.ts
Labels: bug, enhancement

#47 3.7.1のマージ
  src/api/api.ts
  src/common/definitions.ts
  src/common/localsettings.ts
  src/components/pages/EntryPage.vue
  src/components/pages/LoginPage.vue
  src/models/character/loginservice.ts
  src/models/common/ValueUtil.ts
  src/models/status/statusmodel.ts
  src/services/notificationservice.ts
Labels: bug, enhancement

#48 3.7.2のマージ
  src/components/parts/BattleLogView.vue
Labels: enhancement

#49 3.7.3のマージ
  src/components/pages/EntryPage.vue
Labels: bug

#50 3.7.4のマージ
  src/common/definitions.ts
  src/components/pages/StatusPage.vue
Labels: enhancement

#51 3.7.13のマージ
  src/components/parts/SimpleCharacterList.vue
Labels: enhancement

#52 3.7.16のマージ
  src/components/pages/StatusPage.vue
  src/components/parts/status/BattleSimulatorView.vue
Labels: enhancement

#53 3.7.16のマージ
  src/components/parts/status/BattleSimulatorView.vue
Labels: bug

#54 3.7.17のマージ
  src/components/parts/status/BattleSimulatorView.vue
Labels: bug
